{% set name = "pygubu-designer" %}
{% set version = "0.39.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygubu_designer-{{ version }}.tar.gz
  sha256: ad3a6950307ec07684f165545748ebad1c61164ade67b3e74971098af09187df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - appdirs >=1.4.3
    - mako >=1.1.4
    - screeninfo >=0.8
    - autopep8 >=1.7
    - pygubu >=0.35.2

test:
  imports:
    - pygubudesigner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygubu-designer/
  summary: A simple GUI designer for the python tkinter module
  dev_url: https://github.com/alejandroautalan/pygubu-designer
  license: GPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - alejandroautalan
